services:
  - type: web
    name: discador-ia-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
